create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  client_name text not null,
  phone text not null,
  category text,
  category_name text,
  selected_photos jsonb default '[]'::jsonb,
  note text,
  status text default 'Nova seleção'
);
alter table public.orders enable row level security;
create policy "clientes podem criar pedidos" on public.orders for insert to anon with check (true);
-- Para produção, a leitura administrativa deve ser protegida por autenticação Supabase.
